services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
